services:
  db_dj:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_dj:/var/lib/postgresql/data
    ports:
      - "7777:5432"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8100:80"
    depends_on:
      - db_dj
    networks:
      - app_network

  web_dj:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: django_app.settings
      DJANGO_REST_API: ${DJANGO_REST_API}
      DJANGO_REST_API_TOKEN: ${DJANGO_REST_API_TOKEN}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_TEST_HOST: ${DB_TEST_HOST}
    volumes:
      - .:/django_app
    ports:
      - "8001:8001"
    depends_on:
      - db_dj
    networks:
      - app_network

volumes:
  postgres_data_dj:

networks:
  app_network:
    external: true
